name: Tests 🛠️
on:
  pull_request:
  push:
    branches:
    - main
    paths:
    - '**/*.go'
jobs:
  applications-test-units:
    name: "Golang test units"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goVersion: ["1.18", "1.19"]
    steps:
    - name: Checkout project
      uses: actions/checkout@v3
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.goVersion }}
        check-latest: true
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3.3.0
      with:
        version: latest
    - name: Run tests
      run: |
        make test